# Generated by Django 5.0.6 on 2024-07-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_property_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='distance',
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(blank=True, choices=[('Boys only', 'boys only'), ('Girls only', 'girls only'), ('Both', 'both')], max_length=20, null=True),
        ),
    ]
