# Generated by Django 5.0.6 on 2024-07-05 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_remove_property_distance_alter_property_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='rent_per_month',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
