# Generated by Django 5.0.6 on 2024-07-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_property_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.CharField(blank=True, choices=[('available', 'Available'), ('not-available', 'Not-Available')], max_length=20, null=True),
        ),
    ]
